### PR TITLE
fix: properly remove emojis in pretty format with no color

### LINKED ISSUE #764: Emojis are not fully stripped in pretty format with no colors
### What happened?

Audit in pretty format with no colors does not properly strip emojis leaving some broken binary symbols:
```shell
$ polaris audit --audit-path /tmp/1.yaml -f pretty --color=false
[...]
Deployment app
    deploymentMissingReplicas            �� Success
        Reliability - Multiple replicas are scheduled
```

### What did you expect to happen?

No special characters should be present next to the status field.

### How can we reproduce this?

`polaris audit --audit-path <PATH> -f pretty --color=false`

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by weisdd**
This PR fixes #764 

## Checklist
* [x] I have signed the CLA
* [x] I have updated/added any relevant documentation

### What's the goal of this PR?

The goal is to fix emojis removal from pretty outputs in colorless mode. Without the fix, you'd get broken binary symbols, e.g.:
```shell
Deployment app
    deploymentMissingReplicas            �� Success
        Reliability - Multiple replicas are scheduled
```

### What changes did you make?

I haven't seen any double-worded status fields, so instead of slicing, just extracted a word after a whitespace.
```go
status = strings.Fields(status)[1]
```

If there's a need to have such double-worded names, we can replace the code with:
```go
status = strings.Join(strings.Fields(status)[1:], " ")
```
or any other implementation. In Go 1.18, to which the project hasn't migrated yet, there's [strings.Cut()](https://pkg.go.dev/strings#Cut), which I am a fan of. :)

### What alternative solution should we consider, if any?

Not really an alternative, but currently I have to play with `sed` to remove those symbols.

### CODE REVIEW

File: pkg/validator/output.go [hunk 1]
```diff
@@ -211,7 +212,7 @@ func (res ResultSet) GetPrettyOutput() string {
 			}
 		}
 		if color.NoColor {
-			status = status[2:] // remove emoji
+			status = strings.Fields(status)[1] // remove emoji
```
Comment (rbren) [inline pkg/validator/output.go:215]: I wonder if this would be safer as
```
strings.Join(strings.Fields(status)[1:], " ")
```

Comment (rbren) [reply pkg/validator/output.go:215]: Probably not a big deal

**Review by rbren — APPROVED** [review]

File: pkg/validator/output.go (hunk 1 above)
Comment (weisdd) [reply pkg/validator/output.go:248]: @rbren Please, feel free to adjust it to whatever serves the project best :)
